//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepthChartManager.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DepthChartManager.Domain.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League with the same name already exists for this sport.
        /// </summary>
        internal static string LeagueAlreadyExists {
            get {
                return ResourceManager.GetString("LeagueAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid league name.
        /// </summary>
        internal static string LeagueNameIsInvalid {
            get {
                return ResourceManager.GetString("LeagueNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player already exists within the team.
        /// </summary>
        internal static string PlayerAlreadyExistsWithinTeam {
            get {
                return ResourceManager.GetString("PlayerAlreadyExistsWithinTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid player name.
        /// </summary>
        internal static string PlayerNameIsInvalid {
            get {
                return ResourceManager.GetString("PlayerNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid player position.
        /// </summary>
        internal static string PlayerPositionIsInvalid {
            get {
                return ResourceManager.GetString("PlayerPositionIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support position with the same name already exists for this sport.
        /// </summary>
        internal static string SupportPositionAlreadyExists {
            get {
                return ResourceManager.GetString("SupportPositionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid supporting position name.
        /// </summary>
        internal static string SupportPositionNameIsInvalid {
            get {
                return ResourceManager.GetString("SupportPositionNameIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team with the same name already exists.
        /// </summary>
        internal static string TeamAlreadyExists {
            get {
                return ResourceManager.GetString("TeamAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid team name.
        /// </summary>
        internal static string TeamNameIsInvalid {
            get {
                return ResourceManager.GetString("TeamNameIsInvalid", resourceCulture);
            }
        }
    }
}
